### ISSUE TITLE
引入Table.sol合约和自己编写得合约，使用脚手架问题

### ISSUE THREAD

**Issue by D-NN** [WeBankBlockchain/SmartDev-Scaffold#12]
在tools/Contract/引入两个合约文件，Table.sol & DataShare5.sol
生成了DataShare工程文件，
在SmartDev-Scaffold/tools/DataShare/src/main/resources/下
application.properties中填入Table合约的合约地址和DataShare5.sol合约地址，其他节点配置和私钥地址已填入

![按照文档，在gradle bootJar之后出现以下问题](https://images.gitee.com/uploads/images/2021/0603/173943_963f899f_8940447.png "屏幕截图.png")
![输入图片说明](https://images.gitee.com/uploads/images/2021/0603/174816_62576cd1_8940447.png "屏幕截图.png")
![输入图片说明](https://images.gitee.com/uploads/images/2021/0603/174848_a2e65fd0_8940447.png "屏幕截图.png")

**Comment by masonhunk** [comment]
fixed in 1.0.1
