### ISSUE TITLE
3.3.0版本 bug与优化项

### ISSUE THREAD

**Issue by CodingCattwo** [WeBankBlockchain/SmartDev-Scaffold#27]
1 合约构造函数包含struct，报错空指针，Complex合约
2 普通函数包含struct，报错index 0 size 0数组越界，Test合约
3  library 合约生成脚手架会因为abi为空导致空指针

如下图所示
1 问题1
![image](https://github.com/WeBankBlockchain/SmartDev-Scaffold/assets/28867867/1455d202-3078-4c69-8517-1371226c8010)

2  问题2
![image](https://github.com/WeBankBlockchain/SmartDev-Scaffold/assets/28867867/fe37ad0c-1907-4f52-a128-b679d4289e44)

solidity合约，
[2023-07.zip](https://github.com/WeBankBlockchain/SmartDev-Scaffold/files/12037788/2023-07.zip)

**Comment by arc0035** [comment]
这个错误是没有调用java sdk中ContractWrapper类的generateJavaFiles函数，导致内部的struct信息没有被初始化导致的。已经修复，这次修复内容：
1、更新java sdk到3.3.0版本
2、生成java合约到项目构建中
3、修复Complext和Test合约中报错的问题

**Comment by dalaocu** [comment]
# https://github.com/WeBankBlockchain/SmartDev-Scaffold/commit/0a3e5dbf652e9d72410c7670d6d4c96554d7fae7
